INSERT INTO public."ACCOMODATION"(
	"Accomodation_id", "Name", "Type", "Street", "House_num", "City", "Country", "Post_code")
	VALUES ('A1', 'Alpine Lodge', 'Hotel', 'Schönblickstraße', '12', 'Oberstdorf', 'Germany', '87561')
		  ,('A2', 'Hausberg Chalet', 'Chalet', 'Hausbergweg', '2', 'Oberstdorf', 'Germany', '87561')
		  ,('A3', 'Majestic Mountainside Inn', 'Inn', 'Alpenstraße', '4', 'Oberstdorf', 'Germany', '87561')
		  ,('A4', 'Peak View Apartments', 'Apartment', 'Höfatsweg', '8', 'Oberstdorf', 'Germany', '87561')
		  ,('A5', 'Bavarian Mountain Retreat', 'Hotel', 'Kornaustraße', '45', 'Oberstdorf', 'Germany', '87561')
		  ,('A6', 'Alpside Lodge', 'Lodge', 'Lerchenfeldstraße', '17', 'Oberstdorf', 'Germany', '87561')
		  ,('A7', 'Hilltop Guesthouse', 'Guesthouse', 'Am Gaisberg', '9', 'Oberstdorf', 'Germany', '87561')
		  ,('A8', 'Panorama Chalet', 'Chalet', 'Fellhornweg', '28', 'Oberstdorf', 'Germany', '87561')
		  ,('A9', 'Mountain View Hotel', 'Hotel', 'Trettachstraße', '19', 'Oberstdorf', 'Germany', '87561')
		  ,('A10', 'Alpine Vista Apartments', 'Apartment', 'Auenstraße', '3', 'Oberstdorf', 'Germany', '87561')
		  ,('A11', 'Ski Lodge Oberstdorf', 'Lodge', 'Neherstraße', '17', 'Oberstdorf', 'Germany', '87561')
		  ,('A12', 'Alpenrose Guesthouse', 'Guesthouse', 'Mittelbergstraße', '19', 'Oberstdorf', 'Germany', '87561')
		  ,('A13', 'Mountain Breeze Chalet', 'Chalet', 'Höfleweg', '11', 'Oberstdorf', 'Germany', '87561')
		  ,('A14', 'Schattenberg Haus', 'Hotel', 'Schattenbergstraße', '5', 'Oberstdorf', 'Germany', '87561')
		  ,('A15', 'Alpenwald Lodge', 'Lodge', 'Kurparkstraße', '5', 'Oberstdorf', 'Germany', '87561')
		  ,('A16', 'Sonnalp Guesthouse', 'Guesthouse', 'Freibergstraße', '9', 'Oberstdorf', 'Germany', '87561')
		  ,('A17', 'Bavarian Chalet', 'Chalet', 'Wildentalstraße', '29', 'Oberstdorf', 'Germany', '87561')
		  ,('A18', 'Mountain Dream Apartments', 'Apartment', 'Birgsauer Straße', '22', 'Oberstdorf', 'Germany', '87561')
		  ,('A19', 'Alpenglühen Hotel', 'Hotel', 'Eggstraße', '18', 'Oberstdorf', 'Germany', '87561')
		  ,('A20', 'Höllwiesen Haus', 'Guesthouse', 'Kornau-Wanne', '17', 'Oberstdorf', 'Germany', '87561')
		  ,('A21', 'Alpine Lodge', 'Hotel', 'Fellhornstrasse', '20', 'Oberstdorf', 'Germany', '87561'),
		  ,('A22', 'Mount View Inn', 'Bed & Breakfast', 'Lorettostrasse', '4', 'Oberstdorf', 'Germany', '87561')
		  ,('A23', 'Sunny Hillside Chalet', 'Holiday Home', 'Söllereckstrasse', '17', 'Oberstdorf', 'Germany', '87561')
		  ,('A24', 'Snowy Peak Resort', 'Hotel', 'Waltenbergerstrasse', '21', 'Oberstdorf', 'Germany', '87561')
		  ,('A25', 'Mountain View Apartments', 'Apartment', 'Riezlernstrasse', '10', 'Oberstdorf', 'Germany', '87561')
		  ,('A26', 'Alpine Style Pension', 'Pension', 'Hauptstrasse', '35', 'Oberstdorf', 'Germany', '87561')
		  ,('A27', 'The Lodge at Fellhorn', 'Hotel', 'Fellhornstrasse', '15', 'Oberstdorf', 'Germany', '87561')
		  ,('A28', 'Meadowside Guesthouse', 'Guesthouse', 'Söllereckstrasse', '8', 'Oberstdorf', 'Germany', '87561')
		  ,('A29', 'Charming Holiday Home', 'Holiday Home', 'Nebelhornstrasse', '3', 'Oberstdorf', 'Germany', '87561')
		  ,('A30', 'Bavarian Style Chalet', 'Chalet', 'Freibergstrasse', '9', 'Oberstdorf', 'Germany', '87561')
	      ,('A31', 'Walser Lodge', 'Hotel', 'Walserstraße', '50', 'Riezlern', 'Austria', '6991')
          ,('A32', 'Haus Alpenecho', 'Apartment', 'Unterdorf', '23', 'Riezlern', 'Austria', '6991')
          ,('A33', 'Hotel Alpenstern', 'Hotel', 'Walserstraße', '90', 'Riezlern', 'Austria', '6991')
          ,('A34', 'Landhaus Riezler', 'Apartment', 'Walserstraße', '34', 'Riezlern', 'Austria', '6991')
          ,('A35', 'Haus Edelweiss', 'Guest house', 'Kirchplatz', '5', 'Riezlern', 'Austria', '6991')
          ,('A36', 'Gästehaus Alpenblick', 'Guest house', 'Walserstraße', '20', 'Mittelberg', 'Austria', '6993')
          ,('A37', 'Alpenhotel Widderstein', 'Hotel', 'Wildentalstraße', '24', 'Mittelberg', 'Austria', '6993')
          ,('A38', 'Ferienwohnung Susi', 'Apartment', 'Gerschtweg', '11', 'Mittelberg', 'Austria', '6993')
          ,('A39', 'Gästehaus Riezlerhof', 'Guest house', 'Baadstraße', '14', 'Mittelberg', 'Austria', '6993')
          ,('A40', 'Hotel Leitner', 'Hotel', 'Walserstraße', '102', 'Mittelberg', 'Austria', '6993')
          ,('A41', 'Haus am Bach', 'Apartment', 'Bödmenstraße', '35', 'Hirschegg', 'Austria', '6992')
          ,('A42', 'Gästehaus Alpenland', 'Guest house', 'Höfle', '10', 'Hirschegg', 'Austria', '6992')
          ,('A43', 'Kleinwalsertaler Rosenhof', 'Hotel', 'Oberwesteggweg', '9', 'Hirschegg', 'Austria', '6992')
          ,('A44', 'Ferienwohnungen Birkenhof', 'Apartment', 'Gatterhof', '4', 'Hirschegg', 'Austria', '6992')
          ,('A45', 'Hotel Riezler Hof', 'Hotel', 'Walserstraße', '57', 'Riezlern', 'Austria', '6991')
          ,('A46', 'Haus Schäfer', 'Apartment', 'Kirchplatz', '10', 'Riezlern', 'Austria', '6991')
          ,('A47', 'Gästehaus Alpenstern', 'Guest house', 'Höfle', '2', 'Mittelberg', 'Austria', '6993')
          ,('A48', 'Ferienwohnungen Alpina', 'Apartment', 'Walserstraße', '59', 'Riezlern', 'Austria', '6991');





