INSERT INTO public."SHUTTLE"(
	"Shuttle_name", "Type", "Start_location", "End_location", "Capacity", "Area_id")
	VALUES ('Fellhorn I', 'bus', 'Fellhorn valley station', 'Oberstdorf Busstation', '50', 'GF'),
		   ('Fellhorn II', 'bus', 'Oberstdorf Busstation', 'Fellhorn valley station', '50', 'GF'),
		   ('Kanzelwand I', 'bus', 'Kanzelwand valley station', 'Riezlern Post', '50', 'AK'),
		   ('Kanzelwand II', 'bus', 'Riezlern Post', 'Kanzelwand valley station', '50', 'AK'),
		   ('Ifen I', 'bus', 'Ifen valley station', 'Riezlern Post', '50', 'AI'),
		   ('Ifen II', 'bus', 'Riezlern Post', 'Ifen valley station', '50', 'AI'),
		   ('Walmendingerhorn I', 'bus', 'Walmendingerhorn valley station', 'Riezlern Post', '50', 'AW'),
		   ('Walmendingerhorn II', 'bus', 'Riezlern Post', 'Walmendingerhorn valley station', '50', 'AW'),
		   ('Heuberg I', 'bus', 'Heuberg valley station', 'Riezlern Post', '50', 'AH'),
		   ('Heuberg II', 'bus', 'Riezlern Post', 'Heuberg valley station', '50', 'AH'),
		   ('Nebelhorn I', 'bus', 'Nebelhorn valley station', 'Oberstdorf Busstation', '50', 'GN'),
		   ('Nebelhorn II', 'bus', 'Oberstdorf Busstation', 'Fellhorn valley station', '50', 'GN'),
		   ('Söllereck I', 'bus', 'Söllereck valley station', 'Oberstdorf Busstation', '50', 'GS'),
		   ('Söllereck II', 'bus', 'Oberstdorf Busstation', 'Söllereck valley station', '50', 'GS'),
		   ('Sölli I', 'bus', 'Söllereck valley station', 'Kanzelwand valley station', '20', 'GS'),
		   ('Sölli II', 'bus', 'Kanzalwand valley station', 'Söllereck valley station', '20', 'AK'),
		   ('Parsenn I', 'bus', 'Heuberg mountain station', 'Ifen valley station', '20', 'AH'),
		   ('Parsenn II', 'bus', 'Ifen valley station', 'Heuberg mountain station', '20', 'AI'),
		   ('Nebel I', 'bus', 'Nebelhorn valley station', 'Fellhorn valley station', '20', 'GN'),
		   ('Nebel II', 'bus', 'Fellhorn valley station', 'Nebelhorn valley station', '20', 'GF');
