ALTER TABLE IF EXISTS public."EMPLOYEE"
    ADD FOREIGN KEY ("Salary_group")
    REFERENCES public."SALARY" ("Salary_group") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."STUDENT"
    ADD FOREIGN KEY ("Accomodation")
    REFERENCES public."ACCOMODATION" ("Accomodation_id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."STUDENT"
    ADD FOREIGN KEY ("Ski_id")
    REFERENCES public."SKI" ("Ski_id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."STUDENT"
    ADD FOREIGN KEY ("Helmet_id")
    REFERENCES public."HELMETS" ("Helemets_id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."STUDENT"
    ADD FOREIGN KEY ("Pole_id")
    REFERENCES public."POLES" ("Poles_id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."COURSE"
    ADD FOREIGN KEY ("Area")
    REFERENCES public."AREA" ("Area_id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."COURSE"
    ADD FOREIGN KEY ("Employee_id")
    REFERENCES public."EMPLOYEE" ("Employee_id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."COURSE_STUDENT"
    ADD FOREIGN KEY ("COURSE_Course_id")
    REFERENCES public."COURSE" ("Course_id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."COURSE_STUDENT"
    ADD FOREIGN KEY ("STUDENT_Student_id")
    REFERENCES public."STUDENT" ("Student_id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."SHUTTLE"
    ADD FOREIGN KEY ("Area_id")
    REFERENCES public."AREA" ("Area_id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
